services:
  - type: web
    name: bank-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app2:app
    disk:
      name: db
      mountPath: /data
      sizeGB: 1